version: '3.8'

services:
  app:
    image: nxhdev2002/hma-express
    container_name: hma-app
    volumes:
      - ./app:/home/node/app
    ports:
      - "8080:3000"
    environment:
      - "SQL_ADDRESS=10.8.0.254"
      - "SQL_PORT=3306"
      - "SQL_USERNAME=root"
      - "SQL_PASSWORD=ANDROID@QWE@123"
      - "SQL_DATABASE=hma"
      - "PORT=3000"
    command: npm run prod
    network_mode: bridge