version: '3'

services:
  app:
    image: nxhdev2002/hma-express
    container_name: my-node-app
    working_dir: /app
    volumes:
      - ./app:/home/node/app
    ports:
      - "8080:3000"
    user: node
    command: npm run prod
